// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v5.29.0
// source: proto/grpc-project.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'grpc_project';

export interface PaginationDto {
  page: number;
  skip: number;
}

export interface Empty {}

export interface Owners {
  owners: Owner[];
}

export interface CreateOwnerDto {
  username: string;
  password: string;
  age: number;
}

export interface Owner {
  id: string;
  username: string;
  password: string;
  age: number;
  subscribed: boolean;
  socialMedia: SocialMedia | undefined;
}

export interface SocialMedia {
  twitterUrl: string;
}

export const GRPC_PROJECT_PACKAGE_NAME = 'grpc_project';

export interface OwnerServiceClient {
  createOwner(request: CreateOwnerDto): Observable<Owner>;

  findAllOwners(request: Empty): Observable<Owners>;

  queryOwners(request: Observable<PaginationDto>): Observable<Owners>;
}

export interface OwnerServiceController {
  createOwner(
    request: CreateOwnerDto,
  ): Promise<Owner> | Observable<Owner> | Owner;

  findAllOwners(request: Empty): Promise<Owners> | Observable<Owners> | Owners;

  queryOwners(request: Observable<PaginationDto>): Observable<Owners>;
}

export function OwnerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createOwner', 'findAllOwners'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('OwnerService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = ['queryOwners'];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('OwnerService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const OWNER_SERVICE_NAME = 'OwnerService';
