steps:
# Docker-compose build the image. Docker-compose file specifies root context to be able to copy common package.json file.
  - name: docker
    args: ['compose', '-f', 'apps/claims-adjudication/docker-compose.yml', 'build']
# Tag the image with a unique name
  - name: 'docker'
    args: ['tag',
      'claims-adjudication',
      '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA']
# Push the container image to Container Registry (Make sure sahi folder is created)
  - name: 'docker'
    args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'sahi-claims-adjudication', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA', '--region', '$LOCATION', '--allow-unauthenticated',
            '--add-cloudsql-instances', 'pruinhlth-nprd-dev-scxlyx-7250:asia-south1:sahi-dev',
            '--set-env-vars', 'INSTANCE_UNIX_SOCKET=/cloudsql/pruinhlth-nprd-dev-scxlyx-7250:asia-south1:sahi-dev',
            '--set-env-vars', 'INSTANCE_CONNECTION_NAME=pruinhlth-nprd-dev-scxlyx-7250:asia-south1:sahi-dev',
            '--set-env-vars', 'DB_NAME=Claims-Adjudication',
            '--set-env-vars', 'DB_USER=sahi-user',
            '--set-env-vars', 'DB_PASS=qwerty',
            '--set-env-vars', 'SMS_ENABLE=false',
            '--set-env-vars', 'FILE_UPLOAD_ENABLE=false',
            '--set-env-vars', 'DB_USERNAME=sahi-user',
            '--set-env-vars', 'DB_PASSWORD=qwerty',
            '--set-env-vars', 'DB_HOST=/cloudsql/pruinhlth-nprd-dev-scxlyx-7250:asia-south1:sahi-dev',
            '--set-env-vars', 'DB_PORT=5432',
            '--set-env-vars', 'MOCK_SERVICE_BASE_URL=https://mock-service-dnhiaxv6nq-el.a.run.app',
            '--set-env-vars', 'CORE_CLAIM_SERVICE_BASE_URL=https://sahi-core-claims-service-dnhiaxv6nq-el.a.run.app',
            '--set-env-vars', 'ZEEBE_ADDRESS=929779f2-9b29-436e-8962-f71554042990.ont-1.zeebe.camunda.io:443',
            '--set-env-vars', 'ZEEBE_CLIENT_ID=5GJ883BgpG63ERtSw4UCcS4tvH7CO46q',
            '--set-env-vars', 'ZEEBE_CLIENT_SECRET=SRpHqMyaV0FjWuKt.Gx6VMAXKGor6PpMWhlHb294N5W7AhtWIy7mo1RxAGbF0XTZ',
            '--set-env-vars', 'ZEEBE_AUTHORIZATION_SERVER_URL=https://login.cloud.camunda.io/oauth/token',
            '--set-env-vars', 'ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io']
            # '--set-env-vars', 'CAMUNDA_CLUSTER_ID=929779f2-9b29-436e-8962-f71554042990',
            # '--set-env-vars', 'CAMUNDA_CLUSTER_REGION=ont-1',
            # '--set-env-vars', 'CAMUNDA_CREDENTIALS_SCOPES=Zeebe,Operate,Tasklist,Optimize',
            # '--set-env-vars', 'CAMUNDA_TASKLIST_BASE_URL=https://ont-1.tasklist.camunda.io/929779f2-9b29-436e-8962-f71554042990',
            # '--set-env-vars', 'CAMUNDA_OPTIMIZE_BASE_URL=https://ont-1.optimize.camunda.io/929779f2-9b29-436e-8962-f71554042990',
            # '--set-env-vars', 'CAMUNDA_OPERATE_BASE_URL=https://ont-1.operate.camunda.io/929779f2-9b29-436e-8962-f71554042990',
            # '--set-env-vars', 'CAMUNDA_OAUTH_URL=https://login.cloud.camunda.io/oauth/token']

images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA'