steps:
# Docker-compose build the image. Docker-compose file specifies root context to be able to copy common package.json file.
  - name: docker
    args: ['compose', '-f', 'apps/claims-adjudication/docker-compose.yml', 'build']
# Tag the image with a unique name
  - name: 'docker'
    args: ['tag',
      'claims-adjudication',
      '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA']
# Push the container image to Container Registry (Make sure sahi folder is created)
  - name: 'docker'
    args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA']
# Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'sahi-claims-adjudication', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA', '--region', '$LOCATION', '--allow-unauthenticated',
            '--add-cloudsql-instances', 'pruinhlth-nprd-dev-scxlyx-7250:asia-south1:sahi-dev',
            '--set-env-vars', 'DB_NAME=Claims-Adjudication',
            '--set-env-vars', 'SMS_ENABLE=true',
            '--set-env-vars', 'FILE_UPLOAD_ENABLE=false',
            '--set-env-vars', 'DB_USERNAME=sahi-ds-user',
            '--set-env-vars', 'DB_PASSWORD=qwerty',
            '--set-env-vars', 'DB_HOST=35.200.220.140',
            '--set-env-vars', 'DB_PORT=5432',
            '--set-env-vars', 'MOCK_SERVICE_BASE_URL=https://mock-service-dnhiaxv6nq-el.a.run.app',
            '--set-env-vars', 'CORE_CLAIM_SERVICE_BASE_URL=https://sahi-core-claims-service-dnhiaxv6nq-el.a.run.app',
            '--set-env-vars', 'ZEEBE_ADDRESS=31ea074-fd1f-49fc-98c2-6263c29c745e.bru-2.zeebe.camunda.io:443',
            '--set-env-vars', 'ZEEBE_CLIENT_ID=MogcD~cyFnVCe8YLXkeEFxKT2hp95~ju',
            '--set-env-vars', 'ZEEBE_CLIENT_SECRET=rr4x0iePJuL34.loUDw9V-_-QaGltfe3G~iaMU9fAknOsPt6iZrcTcNv~PLToTFX',
            '--set-env-vars', 'ZEEBE_AUTHORIZATION_SERVER_URL=https://login.cloud.camunda.io/oauth/token',
            '--set-env-vars', 'ZEEBE_TOKEN_AUDIENCE=zeebe.camunda.io',
            '--set-env-vars', 'CAMUNDA_CLUSTER_ID=d31ea074-fd1f-49fc-98c2-6263c29c745e',
            '--set-env-vars', 'CAMUNDA_CLUSTER_REGION=bru-2',
            '--set-env-vars', 'CAMUNDA_TASKLIST_BASE_URL=https://bru-2.tasklist.camunda.io/d31ea074-fd1f-49fc-98c2-6263c29c745e',
            '--set-env-vars', 'CAMUNDA_OPTIMIZE_BASE_URL=https://bru-2.optimize.camunda.io/d31ea074-fd1f-49fc-98c2-6263c29c745e',
            '--set-env-vars', 'CAMUNDA_OPERATE_BASE_URL=https://bru-2.operate.camunda.io/d31ea074-fd1f-49fc-98c2-6263c29c745e',
            '--set-env-vars', 'CAMUNDA_OAUTH_URL=https://login.cloud.camunda.io/oauth/token']
            # '--set-env-vars', 'CAMUNDA_CREDENTIALS_SCOPES=Zeebe,Operate,Tasklist,Optimize']

images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/sahi/claims-adjudication:$COMMIT_SHA'